language: julia

os:
  - linux
  - osx

julia:
  - 0.5
  - nightly

# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia --check-bounds=yes -e 'Pkg.clone(pwd())'
#   - julia --check-bounds=yes -e 'Pkg.test("LinearAlgebra")'

after_success:
  - julia -e 'cd(Pkg.dir("LinearAlgebra")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
